import './globals.css';
import Background from '@/components/Background';
import Providers from '@/components/Providers';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'SpendTrack',
  description: 'Generated by Tej',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>SpendTrack</title>
        <meta name="description" content="Track your daily spendings easily" />
        <link rel="icon" href="/logo.svg" type="image/svg+xml" />
      </head>
      <body className="relative min-h-screen text-white">
        <Providers>
          <Background />
          {children}
          <a
            href="https://github.com/TejRJ"
            target="_blank"
            rel="noopener noreferrer"
            className="fixed bottom-4 right-4 z-50 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg shadow-lg transition"
          >
            Contact me - Tej
          </a>
          <ToastContainer
            position="top-right"
            autoClose={3000}
            hideProgressBar={false}
            closeOnClick
            pauseOnHover
            draggable
            theme="dark"
          />
        </Providers>
      </body>
    </html>
  );
}
